feature logger + в pom исправлен parent на spring-boot-starter-parent
nataTerr/online-store-portal pull request #32
Opened 2023-04-14 20:10 UTC by nataTerr

2023-04-22 07:14 UTC, zimin-krsk requested changes

2023-04-22 07:14 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/service/CategoryServiceImpl.java
> +    private static final Logger logger = LoggerFactory.getLogger(CategoryServiceImpl.class);
константы принято писать в самом начале класса\
еще некоторые говорят, что константу logger, как и все остальные, надо писать прописными буквами, но тут я делаю исключение, потому что logger часто используется в коде и это некрасиво

2023-04-22 07:14 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/service/ProductServiceImpl.java
> +                    logger.error("Product with id {} not found", productId);
вот это было бы удобно вынести в GlobalExceptionHandler, тогда все подобные исключения будут обрабатываться одинаково

2023-04-22 07:14 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/service/CategoryServiceImpl.java
> +        logger.info("Find all child categories by parent {} " +
если это и логировать, то только с уровнем `trace`

2023-04-22 07:14 UTC, zimin-krsk commented on site-api/src/main/log/log.2023-04-14.log
вот эти файлы надо в .gitignore добавить, чтобы они в репозиторий не летели

2023-05-15 07:11 UTC, zimin-krsk requested changes

2023-05-15 07:11 UTC, zimin-krsk commented on site-api/src/main/resources/logback.xml
> +            <fileNamePattern>site-api/src/main/log/log.%d{yyyy-MM-dd}.log</fileNamePattern>
кстати, файлы с логами лучше положить в корень модуля site-api, чтобы не путать логи с рабочими файлами

2023-06-17 07:55 UTC, zimin-krsk commented on site-api/src/main/resources/logback.xml
> +            <fileNamePattern>site-api/src/main/log/log.%d{yyyy-MM-dd}.log</fileNamePattern>
сделано в другом ПРе

2023-06-17 08:52 UTC, zimin-krsk approved these changes

2023-06-19 13:40 UTC, merged

2023-06-19 13:40 UTC, nataTerr commented
Closed #31