Feature/junit5
nataTerr/online-store-portal pull request #33
Opened 2023-05-01 08:19 UTC by nataTerr

2023-06-20 20:42 UTC, zimin-krsk commented
надо подтянуть изменения из основной ветки, чтобы изменения по логированию не отображались

2023-06-20 21:04 UTC, zimin-krsk requested changes

2023-06-20 21:04 UTC, zimin-krsk commented on site-api/src/test/java/nata/project/service/CategoryServiceImplMockTest.java
обусждали еще третий тест, который проверит, как хлебные крошки работают для категории первого уровня

2023-06-20 21:04 UTC, zimin-krsk commented on site-api/src/test/java/nata/project/service/ProductServiceImplTest.java
> +    public void saveProductAndGetProductCard() throws Exception {
судя по названию теста ты как будто проверяешь сохранение товара, но это не так.\
товар у тебя уже имеется (блок given), поэтому название метода вводит в заблуждение, лучше переименовать

2023-06-20 21:04 UTC, zimin-krsk commented on site-api/src/test/java/nata/project/service/data/HelperForMockitoData.java
> +    public static List<Category> nullList() {
`emptyList` будет правильнее назвать

2023-06-20 21:04 UTC, zimin-krsk commented on site-api/src/test/resources/application.yaml
> +    password: pgpwd4habr
для тестов пароль можно тоже `postgres` поставить\
удобно запомнить, не надо будет лезть в код, когда придется что-нибудь подебажить

2023-07-01 11:54 UTC, nataTerr commented on site-api/src/test/java/nata/project/service/CategoryServiceImplMockTest.java
А в чем смысл еще одного теста? Результат хлебных крошек мы мокаем и проверяем работу dto.

2023-07-01 11:58 UTC, nataTerr commented
> 



> надо подтянуть изменения из основной ветки, чтобы изменения по логированию не отображались

находясь в своей ветке сделала git merge main, пофиксила конфликты и запушила. Но изменений не вижу

2023-07-03 20:37 UTC, zimin-krsk commented on site-api/src/test/java/nata/project/service/CategoryServiceImplMockTest.java
ну значит я что-то напутал. наверное это в голове отложилось какое-то одно из первых обсуждений :)

2023-07-03 20:43 UTC, zimin-krsk commented
> > 
> 
> > надо подтянуть изменения из основной ветки, чтобы изменения по логированию не отображались
> 
> находясь в своей ветке сделала git merge main, пофиксила конфликты и запушила. Но изменений не вижу

нет, все норм. про логирование не видно изменений больше

2023-07-04 16:52 UTC, nataTerr commented on site-api/src/test/java/nata/project/service/ProductServiceImplTest.java
> +    public void saveProductAndGetProductCard() throws Exception {
+

2023-07-04 16:53 UTC, nataTerr commented on site-api/src/test/java/nata/project/service/data/HelperForMockitoData.java
> +    public static List<Category> nullList() {
+

2023-07-04 16:53 UTC, nataTerr commented on site-api/src/test/resources/application.yaml
> +    password: pgpwd4habr
+

2023-07-04 17:03 UTC, nataTerr commented on site-api/src/test/java/nata/project/service/ProductServiceImplTest.java
> +                .andExpect(mvcResult -> mvcResult.getResolvedException().getClass().equals(ItemNotFoundException.class))
Здесь идеа ругается и я не могу поправить корректно

2023-07-09 09:07 UTC, nataTerr commented on site-api/src/test/java/nata/project/service/ProductServiceImplTest.java
> +                .andExpect(mvcResult -> mvcResult.getResolvedException().getClass().equals(ItemNotFoundException.class))
Строки 68-70, идея ругается, у меня не получилось исправить

2023-07-09 09:07 UTC, nataTerr commented on site-api/src/test/java/nata/project/service/ProductServiceImplTest.java
> +                .andExpect(mvcResult -> mvcResult.getResolvedException().getClass().equals(ItemNotFoundException.class))
![изображение](https://github.com/nataTerr/online-store-portal/assets/83133620/9e05dfed-1615-47b3-ba6e-0777d33cdad8)

2023-07-10 21:14 UTC, zimin-krsk commented on site-api/pom.xml
> +            <scope>runtime</scope>
здесь надо поставить scope=test, как и для зависимости datafactory, которая выше\
чтобы в итоговый jar-файл с приложением эти зависимости не попадали, потому что при обычной работе приложения они не нужны

2023-07-11 08:16 UTC, zimin-krsk approved these changes

2023-07-12 17:01 UTC, merged