uml diagram for order
nataTerr/online-store-portal pull request #34
Opened 2023-07-16 18:07 UTC by nataTerr

2023-07-20 22:08 UTC, zimin-krsk requested changes

2023-07-20 22:08 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +Cart||..o{ Orders
корзина с заказами не должна быть связана, потому как корзина одна для клиента, а заказов может быть много\
или по другому не получается отобразить?

2023-07-20 22:08 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *order_date : timestamp [ (p) ] [ without time zone ]
вместо order_date надо сделать поля: create_date и update_date\
чтобы можно было отдельно смотреть когда заказ создан, а когда был изменен

2023-07-20 22:08 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *order_date : timestamp [ (p) ] [ without time zone ]
вот описание по поводу работы с датой и времен в PostgreSQL:
https://github.com/zimin-krsk/java-juniors-way/pull/1

если будут вопросы - задавай их в комментариях к моему ПРу, заодно поправим, что будет непонятно

2023-07-20 22:08 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *order_date : timestamp [ (p) ] [ without time zone ]
ну и соответственно надо сделать с учетом часового пояса для хранения даты заказа.\
хранение даты обновления информации по заказу можно сделать без учета часового пояса.

2023-08-08 20:34 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +Cart||..o{ Orders
Получается, исправила

2023-08-08 20:34 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *order_date : timestamp [ (p) ] [ without time zone ]
Не совсем понятно зачем изменять заказ... Если ты оформил заказ, то можно его отменить. Из за редактирования заказа может быть много подводных камней.
Но я добавила поле)

2023-08-08 20:34 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *order_date : timestamp [ (p) ] [ without time zone ]
Сделала

2023-08-15 04:00 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *order_date : timestamp [ (p) ] [ without time zone ]
обсудили голосом, что поле update_date может быть использовано программно, при смене статуса заказа, например.

2023-08-15 04:09 UTC, zimin-krsk requested changes

2023-08-15 04:09 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *timeZone for create_date: smallint
лучше сразу описать как поле будет называться в базе, чтобы было однозначное соответствие схемы, миграции и структуры таблицы в постгресе.\
можно назвать `create_date_tz`, например

2023-08-15 04:09 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *delivery_date : timestamp [ (p) ] [ without time zone ]
кстати, для delivery_date тоже пригодится знать часовой пояс. что-то мы об этом забыли, давай добавим

2023-08-15 18:11 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *timeZone for create_date: smallint
Это я тупанула, поправила

2023-08-15 18:11 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *delivery_date : timestamp [ (p) ] [ without time zone ]
Добавила

2023-08-15 20:13 UTC, zimin-krsk requested changes

2023-08-15 20:13 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *update_date_tz : smallint
а вот это не обязательно, т.к. update_date изменяется программно и здесь, на самом деле, важна хронология и не важно в каком часово поясе это произойдет. Но при этом при сохранении данных придется это все обсчитывать.\
Поэтому лучше убрать. Можно даже при сохранении в UTC сразу писать.

2023-08-15 20:31 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *update_date_tz : smallint
Убрала

2023-08-16 04:52 UTC, zimin-krsk requested changes

2023-08-16 04:52 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *create_date_tz: smallint
вот тут, кстати, varchar должен быть, потому что некоторые часовые пояса меняются на 30-45 минут\
поэтому лучше в базе хранить в виде явного смещения: `'+01:00'`, `'+00:30'`, `'-01:00'` и т.д.

2023-08-16 04:52 UTC, zimin-krsk commented on docs/database-uml/order-api.uml
> +  *delivery_date_tz : smallint
тут тоже varchar ))

2023-08-16 08:01 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *create_date_tz: smallint
Исправила

2023-08-16 08:01 UTC, nataTerr commented on docs/database-uml/order-api.uml
> +  *delivery_date_tz : smallint
Исправила

2023-08-17 05:03 UTC, zimin-krsk approved these changes

2023-08-17 08:47 UTC, merged