site-order-open-feign-client
nataTerr/online-store-portal pull request #35
Opened 2023-07-19 16:52 UTC by nataTerr

2023-08-05 05:40 UTC, zimin-krsk requested changes

2023-08-05 05:40 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/controller/OrderController.java
> +    @GetMapping("/orders/{orderId}/detail/info")
можно вынести общую часть пути в аннотацию `@RequestMapping("/orders")` над классом

2023-08-05 05:40 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/entity/Order.java
> +package nata.project.entity;
это не сущность, а транспортный объект (DTO) поэтому уместно будет положить в пакет с другим названием.  
например, т.к. это объекты для ответа по межсервисному взаимодействию, то можно положить их в такой пакет:  `nata.project.model.dto.response.orders`  
тогда сущности могут находиться здесь: `nata.project.model.entity`  

т.о. вся доменная модель будет лежать в пакете model, которая, в свою очередь будет разделяться на дто и сущности.  
дто можно будет дробить по пакетам `request` и `response`, а так же по предметной области, например в одном пакете может лежать все, что относится к заказам, а в другом - что-то иное, например, избранное

2023-08-05 05:40 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/entity/Order.java
> +package nata.project.entity;
в общем если размещать классы системно по пакетам, то в дальнейшем будет понятно где их искать, а так же куда положить новый класс

2023-08-05 05:40 UTC, zimin-krsk commented on site-api/pom.xml
> +<!--            <version>3.0.0</version>-->
а эта версия откуда тянется?

2023-08-05 05:40 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/openFeign/clients/OrderApiFeignClient.java
> +package nata.project.openFeign.clients;
лучше поменять пакеты местами, чтобы следование было от общего к частному - ../clients/feign  
ведь в твоем приложении могут использоваться разные клиенты

2023-08-05 05:40 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/openFeign/dtos/OrderDto.java
> +package nata.project.openFeign.dtos;
все дто можно рядом с клиентами и положить:
- ./clients/feign/dto/request
- ./clients/feign/dto/response

2023-08-05 05:40 UTC, zimin-krsk commented on site-api/src/main/resources/application.yaml
> +#feign.client.config:
вот это пока лучше удалить, потом будут закомментированные строки висеть полгода - лучше добавить, когда будет актуально, ну и разобраться повторно при необходимости

2023-08-05 05:40 UTC, zimin-krsk commented on site-api/src/main/resources/logback.xml
> +            <fileNamePattern>log/log.%d{yyyy-MM-dd}.log</fileNamePattern>
`/log/site-api` может быть тогда?  
а то будут в одном месте логи от сервиса заказов и сервиса сайта лежать

2023-08-08 21:06 UTC, nataTerr commented on site-api/src/main/resources/logback.xml
> +            <fileNamePattern>log/log.%d{yyyy-MM-dd}.log</fileNamePattern>
Не поняла, логи же лежат в модуле site-api

2023-08-08 21:06 UTC, nataTerr commented on site-api/src/main/resources/application.yaml
> +#feign.client.config:
Сделала

2023-08-08 21:07 UTC, nataTerr commented on site-api/src/main/java/nata/project/openFeign/clients/OrderApiFeignClient.java
> +package nata.project.openFeign.clients;
Сделала

2023-08-08 21:07 UTC, nataTerr commented on site-api/pom.xml
> +<!--            <version>3.0.0</version>-->
`<parent>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies-parent</artifactId>
    <version>3.1.8</version>
    <relativePath></relativePath>
  </parent>`

2023-08-08 21:07 UTC, nataTerr commented on order-api/src/main/java/nata/project/entity/Order.java
> +package nata.project.entity;
Поняла, просто изначально я думала потом переписать класс order как сущность.

2023-08-08 21:07 UTC, nataTerr commented on order-api/src/main/java/nata/project/controller/OrderController.java
> +    @GetMapping("/orders/{orderId}/detail/info")
Вынесла

2023-08-10 12:06 UTC, nataTerr commented on site-api/src/main/resources/logback.xml
> +            <fileNamePattern>log/log.%d{yyyy-MM-dd}.log</fileNamePattern>
Исправила

2023-08-10 12:06 UTC, nataTerr commented on site-api/src/main/java/nata/project/openFeign/dtos/OrderDto.java
> +package nata.project.openFeign.dtos;
Сделала

2023-08-10 12:06 UTC, nataTerr commented on site-api/pom.xml
> +<!--            <version>3.0.0</version>-->
Коммент удалила

2023-08-15 04:14 UTC, zimin-krsk requested changes

2023-08-15 04:14 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/dto/response/orders/Order.java
> +    public Order() {
раз используешь Lombok, то можно и для конструкторов аннотации использовать

2023-08-15 18:09 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/dto/response/orders/Order.java
> +    public Order() {
Это да, поправила

2023-08-15 20:13 UTC, zimin-krsk requested changes

2023-08-15 20:13 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/clients/openFeign/controller/OrderApiController.java
> +package nata.project.clients.openFeign.controller;
так, вот это надо обсудить еще. контроллер не должен быть в клиенте.\
в клиенте только то, что относится к емжсервисному взаимодействию. контроллер - это про запросы в site-api

2023-08-15 20:32 UTC, nataTerr commented on site-api/src/main/java/nata/project/clients/openFeign/controller/OrderApiController.java
> +package nata.project.clients.openFeign.controller;
Перенести в контроллер site-api?

2023-08-16 04:51 UTC, zimin-krsk commented on site-api/src/main/java/nata/project/clients/openFeign/controller/OrderApiController.java
> +package nata.project.clients.openFeign.controller;
ага

2023-08-16 08:04 UTC, nataTerr commented on site-api/src/main/java/nata/project/clients/openFeign/controller/OrderApiController.java
> +package nata.project.clients.openFeign.controller;
Перенесла

2023-08-17 05:11 UTC, zimin-krsk approved these changes

2023-08-17 08:47 UTC, merged