migrations and entities
nataTerr/online-store-portal pull request #36
Opened 2023-08-23 19:55 UTC by nataTerr

2023-08-23 21:02 UTC, zimin-krsk requested changes

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Cart.java
> +    List<CartItems> cartItems;
private пропустила

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    Orders orders;
private

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    Orders orders;
название во множественном числе - надо или переименовать или сделать коллекцию заказов

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +public class DeliveryAddress implements Serializable {
`Serializable` не нужен\
Из спецификации: 
> If an entity instance is to be passed by value as a detached object (e.g., through a remote interface), the entity class must implement the Serializable interface.

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +public class Orders implements Serializable {
`Serializable` не нужен

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/OrdersItems.java
> +public class OrdersItems implements Serializable {
`Serializable` не нужен

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    private Delivery orderDelivery;
для перечислений надо дополнительно указывать аннотацию:\
@Enumerated(EnumType.STRING)

https://www.baeldung.com/jpa-persisting-enums-in-jpa#string

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Cart.java
> +    @OneToMany(mappedBy = "cart")
`orphanRemoval = true` можно поставить, чтобы удаленные из коллекции элементы так же удалялись из базы

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    @Column(name = "create_date", columnDefinition = "TIMESTAMP")
`columnDefinition` - это лишнее, судя по описанию в джава доке
> The SQL fragment that is used when generating the DDL for the column.

а у тебя миграции генерируют таблицу - нет смысла объявлять получается - убери везде

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    private PaymentStatus paymentStatus;
здесь тоже надо правильно работу с перечислением объявить

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    private OrderStatus status;
аналогично по работе с перечислениями

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    List<OrdersItems> ordersItems;
private

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    @OneToMany(mappedBy = "orders")
`orphanRemoval = true`

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/enums/Delivery.java
> +    private final String text;
в базу должно сохраняться MAIL, POINT, COURIER\
поле text как будто бы избыточно - зачем оно?

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/enums/Delivery.java
> +    public String getUrl() {
`getUrl()` - опечатка видимо

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/enums/OrderStatus.java
> +    public String getUrl() {
опечатка

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/enums/PaymentStatus.java
> +    public String getUrl() {
опечатка

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/resources/application.yaml
> +    drop-first: true
это точно надо?

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/resources/db/changelog/query_sql/02_create_cart_items.sql
> +    total_amount numeric(12, 2)
total_amount может быть null?

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/resources/db/changelog/query_sql/03_create_delivery_address.sql
> +        create type delivery AS ENUM ('почтой', 'пункт выдачи заказа', 'курьером');
ого! круто, что почитала про такие типы данных в postgresql, но пусть будет строкой - ссылку ранее давал на статью

что-то специфическое для каждой БД лучше использовать в крайних случаях

2023-08-23 21:02 UTC, zimin-krsk commented on order-api/src/main/resources/db/changelog/query_sql/05_create_order_items.sql
> +    total_amount numeric(12, 2)
тут тоже может быть null?

2023-08-24 18:21 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Cart.java
> +    List<CartItems> cartItems;
Исправила

2023-08-24 18:21 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    Orders orders;
Исправила

2023-08-24 18:21 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +public class DeliveryAddress implements Serializable {
Исправила

2023-08-24 18:21 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +public class Orders implements Serializable {
Исправила

2023-08-24 18:21 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/OrdersItems.java
> +public class OrdersItems implements Serializable {
Исправила

2023-08-24 18:21 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    private Delivery orderDelivery;
Сделано

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Cart.java
> +    @OneToMany(mappedBy = "cart")
Сделано и для orders в том числе

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    @Column(name = "create_date", columnDefinition = "TIMESTAMP")
Убрала

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    private PaymentStatus paymentStatus;
Сделано

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    private OrderStatus status;
Сделано

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    List<OrdersItems> ordersItems;
Добавила

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/Orders.java
> +    @OneToMany(mappedBy = "orders")
Сделано

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/enums/Delivery.java
> +    private final String text;
Предполагалось, что в бд тоже будут перечисления и для удобства сопоставления так сделала. Убрала везде, раз в бд это будет строка

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/enums/Delivery.java
> +    public String getUrl() {
Да, но это уже и не нужно, раз значения убрали

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/enums/OrderStatus.java
> +    public String getUrl() {
Убрала

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/enums/PaymentStatus.java
> +    public String getUrl() {
Убрала

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/resources/application.yaml
> +    drop-first: true
Пока тестировала да, исправила на false

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/resources/db/changelog/query_sql/02_create_cart_items.sql
> +    total_amount numeric(12, 2)
Я предполагала, что поле не обязательно к заполнению. Поправила

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/resources/db/changelog/query_sql/03_create_delivery_address.sql
> +        create type delivery AS ENUM ('почтой', 'пункт выдачи заказа', 'курьером');
Сделала строкой для всех enum

2023-08-24 18:22 UTC, nataTerr commented on order-api/src/main/resources/db/changelog/query_sql/05_create_order_items.sql
> +    total_amount numeric(12, 2)
Исправила

2023-08-24 20:12 UTC, zimin-krsk requested changes

2023-08-24 20:12 UTC, zimin-krsk commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    private Orders order;
так название класса тоже в единственном числе пусть будет

2023-08-24 20:22 UTC, nataTerr commented on order-api/src/main/java/nata/project/model/entity/DeliveryAddress.java
> +    private Orders order;
Исправила

2023-08-26 07:54 UTC, zimin-krsk approved these changes

2023-08-26 08:04 UTC, merged